version: '3.3'
services:
    transmission-openvpn:
        cap_add:
            - NET_ADMIN
        volumes:
            - '/home/pkvirus/HHDshare/Torrent-complete:/data'
            - '/home/pkvirus/shared/Transmission/vpn:/config'
        environment:
            - OPENVPN_PROVIDER=cyberghost
            - GITHUB_CONFIG_SOURCE_REPO=PKHarsimran/vpn-configs-contrib
            - OPENVPN_CONFIG=default
            - OPENVPN_USERNAME=************
            - OPENVPN_PASSWORD=***********
            - LOCAL_NETWORK=192.168.4.0/24
        logging:
            driver: json-file
            options:
                max-size: 10m
        ports:
            - '9091:9091'
        image: haugene/transmission-openvpn
